export const ACTIONS = {
    GET_COINS: 'GET_COINS',
    SET_COINS: 'SET_COINS',
    SET_SELECTED_BLOG: 'SET_SELECTED_BLOG',
    SET_COINS_CHAIN: 'SET_COINS_CHAIN',
    SET_SELECTED_COIN: 'SET_SELECTED_COIN',
    SET_TARGET_CURRENCY: 'SET_TARGET_CURRENCY',
    SET_USERS: 'SET_USERS',
    SET_LOGGED_IN_USER: 'SET_LOGGED_IN_USER',
    SET_DUMMY_IMGS: 'SET_DUMMY_IMGS',
    SET_USER_BLOGS: 'SET_USER_BLOGS'
}