export const BACKEND_URL = {
    GET_USERS: '/api/users',
    ADD_USER: '/api/users/createUser',
    LOGIN: '/api/users/login',
    UPDATE_LOGIN_ATTEMPTS: '/api/users/updateLoginAttempts',
    BLOCK_USER: '/api/users/block',
    GET_USER_COINS: '/api/coins/getUserCoins',
    GET_TRANSFER_ADDRESSES: '/api/users/getTransferAddresses',
    TRANSFER_COIN: '/api/coins/transfer',
    GET_COINS: '/api/coins',
    GET_LIVE_COINS: '/api/coins/liveCoins',
    PURCHASE_COIN: '/api/coins/purchase',
    GET_USER_BLOGS: '/api/blogs',
    ADD_NEW_BLOG: '/api/blogs/create',
    UPDATE_BLOG: '/api/blogs/update',
    DELETE_BLOG: '/api/blogs/delete',
}