const Labels = {
    CryptoExchange: 'Crypto-Exchange',
    HomePage: 'Home',
    AboutUs: 'About us',
    Login: 'Login',
    SignUpLogin: 'Signup/Login',
    WelcomeToCryptoWorld: 'Let\'s Explore Crypto World!',
    LoremIpsum: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores in blanditiis necessitatibus voluptas sit doloribus nulla qui nobis, eum nostrum, non quibusdam, a eveniet iure id accusamus provident voluptatum quisquam.Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores in blanditiis necessitatibus voluptas sit doloribus nulla qui nobis, eum nostrum, non quibusdam, a eveniet iure id accusamus provident voluptatum quisquam',
    NoAccount: 'Don\'t have an account?',
    SignUp: 'Sign Up',
    AlreadyAccount: 'Already have an account?',
    FieldRequired: 'This field is required',
    UserAlreadyExists: 'Email already registered!',
    Dashboard: 'Dashboard',
    SignOut: 'Sign out',
    BlogId: 'Blog ID',
    Title: 'Title',
    SubTitle: 'Sub Title',
    Author: 'Author',
    Action: 'Action',
    View: 'View',
    Edit: 'Edit',
    Delete: 'Delete',
    Blogs: 'Blogs',
    ViewBlogDetails: 'View Blog Details',
    EditBlogDetails: 'Edit Blog Details',
    DeleteBlog: 'Delete Blog',
    SureToDelete: 'Are you sure you want to delete this blog?',
    Confirm: 'Confirm',
    Cancel: 'Cancel',
    SaveChanges: 'Save Changes',
    Close: 'Close',
    Save: 'Save',
    NoRecords: 'No Records Found!',
    CreateNewBlog: 'Create New Blog',
    CryptoCoins: 'Crypto Coins',
    CoinName: 'Coin Name',
    CurrentRate: 'Current Rate',
    Transfer: 'Transfer',
    PurchasedCryptoCoins: "Purchased Crypto Coins",
    TransferCoin: 'Transfer Coin',
    SelectCoinChain: 'Select Coin Chain',
    SelectTransferAddress: 'Select Transfer Address',
    Success: 'Success',
    Purchase: 'Purchase',
    CoinPurchasedSuccessfully: 'Coin Purchased Successfully!',
    PurchaseCoins: 'Purchase Coins',
    CoinAlreadyPurchased: 'You have already purchased this coin!'
}

export default Labels;